GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Do laundry"
}

###

DELETE http://localhost:3001/todo/delete/642b18b634e56c64e0c900c1

###

GET http://localhost:3001/todo/complete/642b1befd92774c103fe59e0